services:
  - type: web
    name: omeclone
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: omeclone-db
          property: connectionString
      - key: NODE_ENV
        value: production
    regions: oregon

databases:
  - name: omeclone-db
    plan: free
